include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_dynamic_calls: ignore
    inference_failure_on_function_invocation: ignore
